### ISSUE TITLE
Security issue 

### ISSUE THREAD

**Issue by adlewic** [afoooo/NYCDA#4]
We had a security problem, apparently a wrong key access. 
Orlando helped us and give us the link to the solution of this problem. I attach the link 
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by afoooo** [comment]
Thanks Imelda! I'll look it up!

On Sun, Jun 12, 2016 at 11:52 AM, Imelda Alonso Cervantes <
notifications@github.com> wrote:

> We had a security problem, apparently a wrong key access.
> Orlando helped us and give us the link to the solution of this problem. I
> attach the link
> 
> https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/afoooo/NYCDA/issues/4, or mute the thread
> https://github.com/notifications/unsubscribe/ARuGOe2xyZtrk29EhWd0FmgVZc4T1On4ks5qLCs9gaJpZM4Iz0lX
> .

## 

Confidentiality Notice: The information contained in this email message may
be priviledged, confidential and protected from disclosure. If you are not
the intended recipient, any use, disclosure, dissemination, distribution or
copying of any portion of this message or any attachment is strictly
prohibited. If you think you have received this email message in error,
please notify the sender at the above email address, and delete this email
along with any attachments. Thank you.
